# fly.toml app configuration file generated for react-portfolio-mathis-lefranc on 2023-07-23T12:39:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "react-portfolio-mathis-lefranc"
primary_region = "yyz"

[experimental]
  auto_rollback = true

[env]
  PORT = "8080"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
